version: '3.8'

services:
  sender:
    build: .
    image: hands_on_tcp
    container_name: sender
    hostname: sender
    privileged: true
    tty: true
    networks:
      hands_on_tcp_sender:
        ipv4_address: 172.19.0.3
  receiver:
    build: .
    image: hands_on_tcp
    container_name: receiver
    hostname: receiver
    privileged: true
    tty: true
    networks:
      hands_on_tcp_receiver:
        ipv4_address: 172.20.0.3
  router:
    build: .
    image: hands_on_tcp
    container_name: router
    hostname: router
    privileged: true
    tty: true
    networks:
      hands_on_tcp_sender:
        ipv4_address: 172.19.0.2
      hands_on_tcp_receiver:
        ipv4_address: 172.20.0.2
networks:
  hands_on_tcp_sender:
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16
  hands_on_tcp_receiver:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
